sudo: false

language: erlang
install: 'true'
branches:
  only:
    - master

before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3

env: PATH=$PATH:.

cache:
  - ~/.cache/rebar3

otp_release:
  - 19.3
  - 20.3
  - 21.3
  - 22.3
  - 23.0

script:
  - ./rebar3 do dialyzer, xref, eunit, ct

notifications:
  email: dairon.medina@gmail.com
