sudo: false

language: erlang
install: 'true'
branches:
  only:
    - master

before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3

env: PATH=$PATH:.

cache:
  - ~/.cache/rebar3

otp_release:
  - 21.1
  - 20.3
  - 19.3

script:
  - ./rebar3 test
  - ./rebar3 dialyzer

notifications:
  email: dairon.medina@gmail.com
